export const ACHIEVEMENT_MEDALLION_PATHS = {
  first_trade: "/achievements/medallions/first_trade.webp",
  first_profit: "/achievements/medallions/first_profit.webp",
  first_event: "/achievements/medallions/first_event.webp",
  hundred_trades: "/achievements/medallions/hundred_trades.webp",
  hundred_k_profit: "/achievements/medallions/hundred_k_profit.webp",
  streak_30: "/achievements/medallions/streak_30.webp",
  millionaire: "/achievements/medallions/millionaire.webp",
  top_100: "/achievements/medallions/top_100.webp",
  top_10: "/achievements/medallions/top_10.webp",
  largest_holder: "/achievements/medallions/largest_holder.webp",
  yonko_investor: "/achievements/medallions/yonko_investor.webp",
  pirate_king: "/achievements/medallions/pirate_king.webp",
  market_prophet: "/achievements/medallions/market_prophet.webp",
  diamond_hands: "/achievements/medallions/diamond_hands.webp",
  deckhand_dealer: "/achievements/medallions/deckhand_dealer.webp",
  balanced_ledger: "/achievements/medallions/balanced_ledger.webp",
  million_berry_mover: "/achievements/medallions/million_berry_mover.webp",
  big_score: "/achievements/medallions/big_score.webp",
  treasure_haul: "/achievements/medallions/treasure_haul.webp",
  storm_trader: "/achievements/medallions/storm_trader.webp",
  first_crew: "/achievements/medallions/first_crew.webp",
  crew_builder: "/achievements/medallions/crew_builder.webp",
  grand_fleet: "/achievements/medallions/grand_fleet.webp",
  four_seas_investor: "/achievements/medallions/four_seas_investor.webp",
  rising_bounty: "/achievements/medallions/rising_bounty.webp",
  supernova_fortune: "/achievements/medallions/supernova_fortune.webp",
  emperors_treasury: "/achievements/medallions/emperors_treasury.webp",
  whale_position: "/achievements/medallions/whale_position.webp",
  seven_day_sail: "/achievements/medallions/seven_day_sail.webp",
  seasoned_sailor: "/achievements/medallions/seasoned_sailor.webp",
  unbroken_voyage: "/achievements/medallions/unbroken_voyage.webp",
  king_of_exchange: "/achievements/medallions/king_of_exchange.webp",
  first_sight: "/achievements/medallions/first_sight.webp",
  observation_haki: "/achievements/medallions/observation_haki.webp",
  clue_free_navigator: "/achievements/medallions/clue_free_navigator.webp",
  winning_route: "/achievements/medallions/winning_route.webp",
  grand_line_oracle: "/achievements/medallions/grand_line_oracle.webp",
  first_command: "/achievements/medallions/first_command.webp",
  a_rank_captain: "/achievements/medallions/a_rank_captain.webp",
  s_rank_commander: "/achievements/medallions/s_rank_commander.webp",
  perfect_crew: "/achievements/medallions/perfect_crew.webp",
  mission_log: "/achievements/medallions/mission_log.webp",
  crew_scholar: "/achievements/medallions/crew_scholar.webp",
  grand_fleet_archivist: "/achievements/medallions/grand_fleet_archivist.webp",
} as const;

export type AchievementMedallionCode = keyof typeof ACHIEVEMENT_MEDALLION_PATHS;

export function getAchievementMedallionPath(code: string) {
  return ACHIEVEMENT_MEDALLION_PATHS[code as AchievementMedallionCode] ?? null;
}
